"""Frozen-recipe rendering and render-only republication for model bundles.

First publication renders persisted training/task/generalization recipes and
the combined prediction capture with the configured ``PlotConfig``; a
render-only pass decodes the same versioned documents from a verified
bundle, re-verifies every frozen identity against the summary, and renders
again without touching checkpoints, source datasets, measurements, or any
selection/bootstrap code. Only rendered artifact references and
``rendering.json`` differ in the republished summary.

Contains:
  - ModelRender: rendered files, references and availability outputs.
  - render_model_outputs: render all frozen recipes for one plot config.
  - rendering_document: canonical ``rendering.json`` bytes.
  - render_model_bundle: the ``Result`` render-only boundary.

Satisfies: REQ-AIML-HIGH-004.
"""

from __future__ import annotations

import hashlib
import json
import os
import tomllib
from dataclasses import asdict, dataclass, replace
from pathlib import Path, PurePosixPath
from typing import Any

from flight.libs.types import Err, Ok, Result
from pydantic import TypeAdapter

from tools.ml_models.analysis.artifacts import (
    BundleFile,
    artifact_ref,
    publish_bundle,
)
from tools.ml_models.analysis.capture import CaptureRow
from tools.ml_models.analysis.config import (
    ModelAnalysisConfig,
    PlotConfig,
    config_digest,
    render_digest,
)
from tools.ml_models.analysis.contracts import (
    ArtifactKind,
    ArtifactRef,
    AvailabilityRecord,
    CheckpointIdentity,
    DatasetIdentity,
    SourceSnapshot,
)
from tools.ml_models.analysis.metrics.generalization import (
    BaselineSpec,
    DevelopmentEvidence,
    GeneralizationEvidence,
    MetricReference,
)
from tools.ml_models.analysis.model_figures import ModelFigure
from tools.ml_models.analysis.plots.model import render_model_figures
from tools.ml_models.analysis.plots.training import render_training_figures
from tools.ml_models.analysis.prediction_selections import PredictionGallery
from tools.ml_models.analysis.summaries import ModelTrainingSummary
from tools.ml_models.analysis.training import TrainingExecution
from tools.ml_models.analysis.training_figures import TrainingFigure
from tools.ml_models.analysis.visuals.predictions import (
    PredictionPreview,
    PredictionPreviewCapture,
    render_prediction_visuals,
)
from tools.ml_models.train.config import TrainConfig

_RENDER_NAMESPACES = ("model_figure:", "training_figure:", "prediction_visual:")
_RENDER_PATH = "rendering.json"
_FRESH = "frozen recipes are missing or unreadable; fresh analyze required"
_EVIDENCE_FIELDS = frozenset(
    {
        "schema_version",
        "kind",
        "training_dataset",
        "evaluation_dataset",
        "checkpoint",
        "config_digest",
        "config",
        "baseline",
        "generalization",
        "development",
        "resources",
        "metric_reference",
        "outputs",
        "warnings",
        "source_snapshots",
    }
)


@dataclass(frozen=True, slots=True)
class ModelRender:
    """Rendered figure/visual bytes, references and availability records."""

    files: tuple[BundleFile, ...]
    refs: tuple[ArtifactRef, ...]
    outputs: tuple[AvailabilityRecord, ...]


def _canonical(values: object) -> bytes:
    """Encode finite canonical JSON without creating an output directory."""
    return json.dumps(values, sort_keys=True, allow_nan=False, separators=(",", ":")).encode(
        "utf-8"
    )


def _refs(
    files: tuple[BundleFile, ...], kind: ArtifactKind, population: str
) -> Result[tuple[ArtifactRef, ...], str]:
    """Bind generated bytes to explicit kinds/populations without touching output."""
    refs: list[ArtifactRef] = []
    for file in files:
        ref = artifact_ref(
            file.path,
            file.data,
            kind=kind,
            format=file.path.rsplit(".", 1)[-1],
            population=population,
        )
        if isinstance(ref, Err):
            return ref
        refs.append(ref.value)
    return Ok(tuple(refs))


def render_model_outputs(
    training_figures: tuple[TrainingFigure, ...],
    task_figures: tuple[ModelFigure, ...],
    generalization_figures: tuple[ModelFigure, ...],
    previews: PredictionPreviewCapture,
    kind: str,
    cfg: PlotConfig,
) -> Result[ModelRender, str]:
    """Render every frozen recipe and gallery under ``figures``/``visuals``.

    Recipes render exactly as frozen: unavailable records produce indexed
    placeholders, and the shared prediction capture renders one combined
    gallery set. Nothing is measured, selected or recomputed here.
    """
    files: list[BundleFile] = []
    outputs: list[AvailabilityRecord] = []
    for rendered in (
        render_training_figures(training_figures, cfg),
        render_model_figures(task_figures, cfg, family=kind),
        render_model_figures(generalization_figures, cfg, family="generalization"),
    ):
        if isinstance(rendered, Err):
            return rendered
        files.extend(rendered.value.files)
        outputs.extend(rendered.value.outputs)
    figure_files = tuple(files)
    figure_refs = _refs(figure_files, "FIGURE", "frozen rendered model figure")
    if isinstance(figure_refs, Err):
        return figure_refs
    visuals = render_prediction_visuals(previews, cfg)
    if isinstance(visuals, Err):
        return visuals
    visual_refs = _refs(visuals.value.files, "VISUAL", "frozen bounded prediction previews")
    if isinstance(visual_refs, Err):
        return visual_refs
    outputs.extend(visuals.value.outputs)
    outputs.insert(
        0,
        AvailabilityRecord(name="figures", status="AVAILABLE", required=True),
    )
    outputs.append(
        AvailabilityRecord(
            name="visuals",
            status="AVAILABLE" if visuals.value.files else "SKIPPED",
            reason=None
            if visuals.value.files
            else "No prediction preview galleries were recorded in the frozen capture",
        )
    )
    return Ok(
        ModelRender(
            figure_files + visuals.value.files,
            figure_refs.value + visual_refs.value,
            tuple(outputs),
        )
    )


def rendering_document(measurement_id: str, plot: PlotConfig) -> Result[bytes, str]:
    """Serialize ``rendering.json`` binding the render identity to the measurement."""
    try:
        digest = render_digest(measurement_id, plot)
    except ValueError as exc:
        return Err(f"cannot bind render identity: {exc}")
    return Ok(
        _canonical(
            {
                "measurement_id": measurement_id,
                "render_id": digest,
                "plot": asdict(plot),
                "method": "model_render_v1",
            }
        )
    )


def _canonical_json(value: object) -> object:
    """Normalize one value through canonical JSON so tuple/list forms agree."""
    return json.loads(_canonical(value))


def _reject_constant(value: str) -> object:
    raise ValueError(f"non-finite JSON constant {value}")


def _json_object(raw: bytes, path: str) -> Result[dict[str, object], str]:
    """Parse one frozen JSON document strictly."""
    try:
        payload = json.loads(raw, parse_constant=_reject_constant)
    except (json.JSONDecodeError, ValueError) as exc:
        return Err(f"{path}: {_FRESH} ({exc})")
    if not isinstance(payload, dict):
        return Err(f"{path}: {_FRESH} (document must be an object)")
    return Ok(payload)


def _version_is_one(version: object) -> bool:
    """True only for the integer schema version 1; booleans are rejected."""
    return isinstance(version, int) and not isinstance(version, bool) and version == 1


def _decode_figures[T](
    raw: bytes, path: str, adapter: TypeAdapter[tuple[T, ...]]
) -> Result[tuple[T, ...], str]:
    """Decode one versioned figure-document payload into typed recipes."""
    document = _json_object(raw, path)
    if isinstance(document, Err):
        return document
    if not _version_is_one(document.value.get("schema_version")) or (
        "figures" not in document.value
    ):
        return Err(f"{path}: {_FRESH} (unsupported figure document)")
    try:
        return Ok(adapter.validate_python(document.value["figures"]))
    except ValueError as exc:
        return Err(f"{path}: {_FRESH} ({exc})")


def _linked(path: Path) -> bool:
    """True when any component of ``path``, including ancestors, is a link."""
    current = path
    while True:
        if os.path.islink(current) or os.path.isjunction(current):
            return True
        if current.parent == current:
            return False
        current = current.parent


def _bundle_files(root: Path, summary: ModelTrainingSummary) -> Result[dict[str, bytes], str]:
    """Read every referenced bundle file; ``verify_bundle`` already checksummed it."""
    resolved_root = root.resolve()
    files: dict[str, bytes] = {}
    for ref in summary.artifacts:
        target = root.joinpath(*PurePosixPath(ref.path).parts)
        try:
            if not target.resolve().is_relative_to(resolved_root):
                return Err(f"bundle file {ref.path} escapes the evidence bundle")
        except (OSError, ValueError, RuntimeError) as exc:
            return Err(f"cannot resolve bundle file {ref.path}: {exc}")
        if _linked(target):
            return Err(f"bundle file {ref.path} contains a symlink or junction component")
        try:
            files[ref.path] = target.read_bytes()
        except OSError as exc:
            return Err(f"cannot read bundle file {ref.path}: {_FRESH} ({exc})")
        if len(files[ref.path]) != ref.size_bytes or (
            hashlib.sha256(files[ref.path]).hexdigest() != ref.sha256
        ):
            return Err(f"bundle file {ref.path} changed since verification")
    return Ok(files)


def _authoritative_rows(files: dict[str, bytes]) -> Result[frozenset[str], str]:
    """Canonical-JSON index of every captured row recorded in rows.jsonl files."""
    rows: set[str] = set()
    adapter = TypeAdapter(CaptureRow)
    for path, data in files.items():
        if not (path.startswith("capture/") and path.endswith("/rows.jsonl")):
            continue
        for line in data.splitlines():
            if not line.strip():
                continue
            try:
                row = adapter.validate_json(line)
            except ValueError as exc:
                return Err(f"{path}: {_FRESH} ({exc})")
            rows.add(_canonical(asdict(row)).decode("utf-8"))
    return Ok(frozenset(rows))


def _decode_model_recipes(
    files: dict[str, bytes], summary: ModelTrainingSummary
) -> Result[
    tuple[
        tuple[TrainingFigure, ...],
        tuple[ModelFigure, ...],
        tuple[ModelFigure, ...],
        PredictionPreviewCapture,
    ],
    str,
]:
    """Decode every persisted recipe and the combined prediction capture."""
    kind = summary.checkpoint.kind
    paths = (
        "training-figure-data.json",
        f"task/{kind}/model-figure-data.json",
        "generalization/model-figure-data.json",
        "prediction-manifest.json",
    )
    missing = [path for path in paths if path not in files]
    if missing:
        return Err(f"{sorted(missing)}: {_FRESH}")
    training = _decode_figures(
        files["training-figure-data.json"],
        "training-figure-data.json",
        TypeAdapter(tuple[TrainingFigure, ...]),
    )
    if isinstance(training, Err):
        return training
    task = _decode_figures(
        files[f"task/{kind}/model-figure-data.json"],
        f"task/{kind}/model-figure-data.json",
        TypeAdapter(tuple[ModelFigure, ...]),
    )
    if isinstance(task, Err):
        return task
    generalization = _decode_figures(
        files["generalization/model-figure-data.json"],
        "generalization/model-figure-data.json",
        TypeAdapter(tuple[ModelFigure, ...]),
    )
    if isinstance(generalization, Err):
        return generalization
    manifest = _json_object(files["prediction-manifest.json"], "prediction-manifest.json")
    if isinstance(manifest, Err):
        return manifest
    if manifest.value.get("schema_version") != 1:
        return Err(f"prediction-manifest.json: {_FRESH} (unsupported schema)")
    try:
        previews = TypeAdapter(tuple[PredictionPreview, ...]).validate_python(
            manifest.value["previews"]
        )
        galleries = TypeAdapter(tuple[PredictionGallery, ...]).validate_python(
            manifest.value["galleries"]
        )
    except (KeyError, ValueError) as exc:
        return Err(f"prediction-manifest.json: {_FRESH} ({exc})")
    preview_files: list[BundleFile] = []
    for preview in previews:
        data = files.get(preview.path)
        if data is None:
            return Err(f"{preview.path}: {_FRESH} (preview file is not referenced)")
        if len(data) != preview.size_bytes or hashlib.sha256(data).hexdigest() != preview.sha256:
            return Err(f"{preview.path}: {_FRESH} (preview bytes differ)")
        preview_files.append(BundleFile(preview.path, data))
    captured = _authoritative_rows(files)
    if isinstance(captured, Err):
        return captured
    rows = [row for gallery in galleries for row in gallery.rows] + [
        preview.row for preview in previews
    ]
    splits = {(split.task, split.split, split.dataset_hash) for split in summary.splits}
    for row in rows:
        if (row.key.task, row.key.split, row.key.dataset_hash) not in splits:
            return Err(f"captured row identities disagree with the summary: {_FRESH}")
        if _canonical(asdict(row)).decode("utf-8") not in captured.value:
            return Err(f"preview row is not an authoritative captured row: {_FRESH}")
    split_by_identity = {(split.task, split.split): split for split in summary.splits}
    for record in (*task.value, *generalization.value):
        split = split_by_identity.get((record.identity.task, record.identity.split))
        if (
            split is None
            or record.identity.dataset_hash != split.dataset_hash
            or record.identity.dataset_manifest_hash != split.dataset_manifest_hash
            or record.identity.checkpoint_hash != split.checkpoint_hash
            or record.identity.task != split.task
            or record.identity.split != split.split
        ):
            return Err(f"frozen figure identities disagree with the summary: {_FRESH}")
    return Ok(
        (
            training.value,
            task.value,
            generalization.value,
            PredictionPreviewCapture(previews, tuple(preview_files), galleries),
        )
    )


def _replace_rendered(
    summary: ModelTrainingSummary,
    rendered: ModelRender,
    rendering_ref: ArtifactRef,
) -> ModelTrainingSummary:
    """Swap only rendered refs/outputs; scientific identity stays byte-identical."""
    kept_refs = tuple(
        ref
        for ref in summary.artifacts
        if ref.kind not in ("FIGURE", "VISUAL") and ref.path != _RENDER_PATH
    )
    kept_outputs = tuple(
        record
        for record in summary.outputs
        if record.name not in ("figures", "visuals")
        and not record.name.startswith(_RENDER_NAMESPACES)
    )
    return replace(
        summary,
        artifacts=kept_refs + rendered.refs + (rendering_ref,),
        outputs=kept_outputs + rendered.outputs,
    )


def _decode_evidence(raw: bytes, path: str) -> Result[dict[str, object], str]:
    """Strictly decode the version-1 frozen model evidence document."""
    document = _json_object(raw, path)
    if isinstance(document, Err):
        return document
    payload = document.value
    unknown = set(payload) - _EVIDENCE_FIELDS
    if unknown:
        return Err(f"{path}: {_FRESH} (unknown document fields {sorted(unknown)})")
    missing = _EVIDENCE_FIELDS - set(payload)
    if missing:
        return Err(f"{path}: {_FRESH} (missing document fields {sorted(missing)})")
    if not _version_is_one(payload.get("schema_version")):
        return Err(f"{path}: {_FRESH} (unsupported schema version)")
    if payload.get("kind") != "MODEL_ANALYSIS_EVIDENCE":
        return Err(f"{path}: {_FRESH} (unsupported document kind)")
    from tools.ml_models.analysis.model_measurement import ModelResource

    expectations: tuple[tuple[str, TypeAdapter[Any]], ...] = (
        ("training_dataset", TypeAdapter(DatasetIdentity)),
        ("evaluation_dataset", TypeAdapter(DatasetIdentity)),
        ("checkpoint", TypeAdapter(CheckpointIdentity)),
        ("config", TypeAdapter(ModelAnalysisConfig)),
        ("baseline", TypeAdapter(BaselineSpec)),
        ("generalization", TypeAdapter(tuple[GeneralizationEvidence, ...])),
        ("development", TypeAdapter(DevelopmentEvidence | None)),
        ("resources", TypeAdapter(tuple[ModelResource, ...])),
        ("metric_reference", TypeAdapter(tuple[MetricReference, ...])),
        ("outputs", TypeAdapter(tuple[AvailabilityRecord, ...])),
        ("warnings", TypeAdapter(tuple[str, ...])),
        ("source_snapshots", TypeAdapter(tuple[SourceSnapshot, ...])),
    )
    for field, adapter in expectations:
        try:
            adapter.validate_python(payload[field])
        except ValueError as exc:
            return Err(f"{path}: {_FRESH} ({field}: {exc})")
    return Ok(payload)


def _contained(path: Path, root: Path) -> bool:
    """True when resolved ``path`` lies at or below resolved ``root``."""
    try:
        return path.resolve().is_relative_to(root.resolve())
    except OSError, ValueError, RuntimeError:
        return True


def render_model_bundle(
    root: Path, summary: ModelTrainingSummary, cfg: PlotConfig, out: Path
) -> Result[Path, str]:
    """Re-render a verified model bundle with a new plot config; never re-measure.

    ``verify_bundle`` has already validated every reference; this decodes the
    frozen ``model-evidence.json`` document and versioned recipes, checks them
    against the summary identities, then republishes to a fresh exclusive
    output with byte-identical scientific files.
    """
    try:
        if out.resolve().is_relative_to(root.resolve()):
            return Err(f"render output {out} lies inside the evidence bundle")
        evidence_path = "model-evidence.json"
        files = _bundle_files(root, summary)
        if isinstance(files, Err):
            return files
        if evidence_path not in files.value:
            return Err(f"{evidence_path}: {_FRESH}")
        document = _decode_evidence(files.value[evidence_path], evidence_path)
        if isinstance(document, Err):
            return document
        if (
            document.value["checkpoint"] != _canonical_json(asdict(summary.checkpoint))
            or document.value["training_dataset"]
            != _canonical_json(asdict(summary.training_dataset))
            or document.value["evaluation_dataset"]
            != _canonical_json(asdict(summary.evaluation_dataset))
            or document.value["config_digest"] != summary.config_digest
        ):
            return Err(f"{evidence_path}: {_FRESH} (frozen identities disagree)")
        config_raw = files.value.get("config.toml")
        if config_raw is None:
            return Err(f"config.toml: {_FRESH}")
        try:
            parsed = TypeAdapter(ModelAnalysisConfig).validate_python(
                tomllib.loads(config_raw.decode("utf-8"))
            )
        except (tomllib.TOMLDecodeError, UnicodeDecodeError, ValueError) as exc:
            return Err(f"config.toml: {_FRESH} ({exc})")
        if config_digest(parsed) != summary.config_digest:
            return Err(f"config.toml: {_FRESH} (scientific settings digest differs)")
        if document.value["config"] != _canonical_json(asdict(parsed)):
            return Err(f"{evidence_path}: {_FRESH} (config snapshot differs)")
        baseline = TypeAdapter(BaselineSpec).validate_python(document.value["baseline"])
        if baseline.training_dataset_hash != summary.training_dataset.content_hash:
            return Err(f"{evidence_path}: {_FRESH} (baseline train identity differs)")
        split_by_name = {(split.task, split.split): split for split in summary.splits}
        for record in TypeAdapter(tuple[GeneralizationEvidence, ...]).validate_python(
            document.value["generalization"]
        ):
            split = split_by_name.get((record.task, record.split))
            if (
                split is None
                or record.dataset_hash != split.dataset_hash
                or record.dataset_manifest_hash != split.dataset_manifest_hash
                or record.score_config != parsed.score
            ):
                return Err(f"{evidence_path}: {_FRESH} (generalization identities differ)")
        development: DevelopmentEvidence | None = TypeAdapter(
            DevelopmentEvidence | None
        ).validate_python(document.value["development"])
        if development is not None and (
            development.checkpoint_hash != summary.checkpoint.sha256
            or development.dataset_hash != summary.evaluation_dataset.content_hash
            or development.dataset_manifest_hash != summary.evaluation_dataset.manifest_hash
            or development.score_config != parsed.score
        ):
            return Err(f"{evidence_path}: {_FRESH} (development identity differs)")
        refs = {ref.path: ref for ref in summary.artifacts}
        snapshots = TypeAdapter(tuple[SourceSnapshot, ...]).validate_python(
            document.value["source_snapshots"]
        )
        expected_sources = {path for path in refs if path.startswith("source/")}
        seen_sources: set[str] = set()
        for entry in snapshots:
            if entry.path in seen_sources:
                return Err(f"{evidence_path}: {_FRESH} (duplicate source snapshot)")
            seen_sources.add(entry.path)
            ref = refs.get(entry.path)
            if ref is None or ref.sha256 != entry.sha256 or ref.size_bytes != entry.size_bytes:
                return Err(f"{evidence_path}: {_FRESH} (source snapshot refs disagree)")
        if seen_sources != expected_sources:
            return Err(f"{evidence_path}: {_FRESH} (source snapshots do not cover the refs)")
        frozen_cfg = TypeAdapter(ModelAnalysisConfig).validate_python(document.value["config"])
        source_config_raw = files.value.get("source/config.toml")
        source_execution_raw = files.value.get("source/execution.json")
        train_manifest_raw = files.value.get("source/training-dataset.json")
        eval_manifest_raw = files.value.get("source/evaluation-dataset.json")
        if (
            source_config_raw is None
            or source_execution_raw is None
            or train_manifest_raw is None
            or eval_manifest_raw is None
        ):
            return Err(f"{evidence_path}: {_FRESH} (required source snapshots are missing)")
        try:
            source_cfg = TypeAdapter(TrainConfig).validate_python(
                tomllib.loads(source_config_raw.decode("utf-8"))
            )
        except (tomllib.TOMLDecodeError, UnicodeDecodeError, ValueError) as exc:
            return Err(f"source/config.toml: {_FRESH} ({exc})")
        source_execution = _json_object(source_execution_raw, "source/execution.json")
        if isinstance(source_execution, Err):
            return source_execution
        try:
            execution = TypeAdapter(TrainingExecution).validate_python(source_execution.value)
        except ValueError as exc:
            return Err(f"source/execution.json: {_FRESH} ({exc})")
        if _canonical_json(asdict(source_cfg)) != _canonical_json(execution.config):
            return Err(f"source/config.toml: {_FRESH} (recorded execution config differs)")
        selected = execution.best if frozen_cfg.checkpoint == "best" else execution.last
        if selected is None or selected.identity != summary.checkpoint:
            return Err(f"{evidence_path}: {_FRESH} (selected checkpoint identity differs)")
        if hashlib.sha256(train_manifest_raw).hexdigest() != summary.training_dataset.manifest_hash:
            return Err(f"{evidence_path}: {_FRESH} (training manifest snapshot differs)")
        if (
            hashlib.sha256(eval_manifest_raw).hexdigest()
            != summary.evaluation_dataset.manifest_hash
        ):
            return Err(f"{evidence_path}: {_FRESH} (evaluation manifest snapshot differs)")
        forbidden_roots = [Path(frozen_cfg.run), Path(source_cfg.dataset)]
        if frozen_cfg.dataset is not None:
            forbidden_roots.append(Path(frozen_cfg.dataset))
        if any(_contained(out, forbidden) for forbidden in forbidden_roots):
            return Err(f"render output {out} lies inside a recorded source path")
        recipes = _decode_model_recipes(files.value, summary)
        if isinstance(recipes, Err):
            return recipes
        training, task, generalization, previews = recipes.value
        rendered = render_model_outputs(
            training, task, generalization, previews, summary.checkpoint.kind, cfg
        )
        if isinstance(rendered, Err):
            return rendered
        old_render_outputs = {
            record.name: (record.status, record.reason)
            for record in summary.outputs
            if record.name in ("figures", "visuals") or record.name.startswith(_RENDER_NAMESPACES)
        }
        new_render_outputs = {
            record.name: (record.status, record.reason) for record in rendered.value.outputs
        }
        if old_render_outputs != new_render_outputs:
            return Err(f"rendered outputs do not match the frozen availability index: {_FRESH}")
        document_bytes = rendering_document(summary.measurement_id, cfg)
        if isinstance(document_bytes, Err):
            return document_bytes
        rendering_ref = artifact_ref(
            _RENDER_PATH, document_bytes.value, kind="REFERENCE", format="json"
        )
        if isinstance(rendering_ref, Err):
            return rendering_ref
        new_summary = _replace_rendered(summary, rendered.value, rendering_ref.value)
        bundle_files = (
            tuple(
                BundleFile(ref.path, files.value[ref.path])
                for ref in summary.artifacts
                if ref.kind not in ("FIGURE", "VISUAL") and ref.path != _RENDER_PATH
            )
            + rendered.value.files
            + (BundleFile(_RENDER_PATH, document_bytes.value),)
        )
        return publish_bundle(out, new_summary, bundle_files)
    except (OSError, ValueError, TypeError, RuntimeError, OverflowError) as exc:
        return Err(f"model bundle rendering failed before publication: {exc}")
