"""Markdown reports for the single-axis vs dual-axis gimbal study.

``write_geometry_report`` writes RESULTS.md (design-pass geometry).
``write_industry_report`` writes INDUSTRIAL.md (world stack inventory).
Both are generated artifacts, not STE descriptive docs.

Contains:
  - write_geometry_report / write_industry_report.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from analysis.lib.tracking import TimeLostFn
from analysis.studies.single_axis_vs_dual_axis_gimbal.assumptions import (
    BAND_ALONG_PX,
    BAND_LATERAL_PX,
    CLS_FLOPS_256_G,
    CLS_LAT_256_MS,
    CLUSTER_R_KM,
    DESIGN_LAT_DEG,
    GIMBAL_BOX,
    OPTICS_SPEC,
    SEG_FLOPS_256_G,
    SEG_LAT_256_MS,
    TLE,
    WIND_MPS,
)
from analysis.studies.single_axis_vs_dual_axis_gimbal.inventory import Cluster

if TYPE_CHECKING:
    from analysis.studies.single_axis_vs_dual_axis_gimbal.geometry import GeometryResult

_RUN_CMD = "uv run python -m analysis.studies.single_axis_vs_dual_axis_gimbal"


def write_geometry_report(result: GeometryResult, path: Path) -> None:
    """Write RESULTS.md for the design-pass geometry.

    Args:
        result: Design-pass tables.
        path: Output markdown path.

    Returns:
        None.
    """
    import math

    orbit = result.orbit
    optics = result.optics
    times = result.times
    table = result.table
    times_perigee = result.times_perigee
    h_km = times.local_alt_km
    r_fit = h_km * math.tan(math.radians(optics.half_az_deg))
    r_box = h_km * math.tan(math.radians(GIMBAL_BOX.az_box_deg))
    area_256 = 256 * 256
    area_ff = BAND_LATERAL_PX * BAND_ALONG_PX
    scale = area_ff / area_256
    lines: list[str] = []
    a = lines.append
    a("# Single-axis gimbal tracking time")
    a("")
    a("TEMPORARY ANALYSIS. Generated by the geometry command of")
    a(f"`{_RUN_CMD}`. Not flight software.")
    a("")
    a("## Locked assumptions")
    a("")
    a("From the 2026-09-01 follow-up:")
    a("")
    a("- Elevation window is **one-sided** 90->30 deg. Hard gimbal stops for")
    a("  clearance; tracking time stops at the limit, with no leftover FOV walk-out.")
    a("- Mount is geocentric nadir. A <=5 deg offset is a later correction, not in")
    a("  this run.")
    a("- At most **one plant cluster** per track. Elevation follows the cluster")
    a("  CoG. Science is satisfied if a plume is **anywhere in the frame**, so the")
    a("  success metric is a covering disk of radius R around that CoG, not")
    a("  boresight centering.")
    a("- If plants are spread farther than the chip (~+/-12 km at nadir), CoG is")
    a("  the wrong metric: pick the nearest/brightest cluster and treat it as")
    a("  its own origin. Do not average across a city.")
    a("- Current ISS TLE (Celestrak GP, epoch 2026-09-01). Earth rotation and")
    a("  51.63 deg inclination are on. Design pass is **max latitude** (heading")
    a("  due east), which is the polar-most nadir ISS can reach.")
    a("- FOV is the **most restrictive**: IMX264 active area, then shrunk by the")
    a("  lens max distortion of 0.66 %. The 8.8 mm 2/3-inch sheet HFOV of 3.36 deg")
    a("  is larger than this camera and is not used.")
    a("- Full-frame inference = the full 2x2 band plane. That does not change")
    a("  optical FOV; it is a compute note.")
    a("- A ~2028 launch still sits in the current 416-423 km operational band.")
    a("  ISS is committed through 2030; retrograde deorbit lowering is a")
    a("  2028-2030 lead-up, not a 2028 operations baseline.")
    a("")
    a("## ISS orbit (TLE 25544, 2026-09-01)")
    a("")
    a("| Quantity | Value |")
    a("| --- | --- |")
    a(f"| Inclination | {TLE.inclination_deg:.4f} deg |")
    a(f"| Eccentricity | {TLE.eccentricity:.7f} |")
    a(f"| Mean motion | {TLE.mean_motion_rev_per_day:.8f} rev/day |")
    a(f"| Period | {orbit.period_s / 60.0:.3f} min |")
    a(f"| SMA | {orbit.sma_km:.2f} km |")
    a(f"| Mean altitude (WGS84 equator) | {orbit.mean_alt_eq_km:.2f} km |")
    a(
        f"| Perigee / apogee altitude | "
        f"{orbit.perigee_alt_eq_km:.2f} / {orbit.apogee_alt_eq_km:.2f} km |"
    )
    a(f"| Inertial speed (SMA) | {orbit.v_km_s:.3f} km/s |")
    a(f"| Local altitude at lat {DESIGN_LAT_DEG:.2f} deg | **{h_km:.2f} km** |")
    a(f"| Local altitude at perigee, same lat | {times_perigee.local_alt_km:.2f} km |")
    a("")
    a("A ~2028 launch does not change this band. NASA holds ~415 km through")
    a("2030; debris risk rises if the station is boosted higher. Perigee in this")
    a(f"TLE is {orbit.perigee_alt_eq_km:.1f} km equatorial; the one-sided window")
    a(f"there is {times_perigee.along_track_s:.1f} s vs {times.along_track_s:.1f} s at SMA.")
    a("")
    a("## Optics (most restrictive)")
    a("")
    a("| Quantity | Value |")
    a("| --- | --- |")
    a(f"| Array | {OPTICS_SPEC.n_lateral_px} x {OPTICS_SPEC.n_along_px} (lateral x along-track) |")
    a(f"| Active area | {optics.sensor_width_mm:.3f} x {optics.sensor_height_mm:.3f} mm |")
    a(f"| Thin-lens FOV | {optics.fov_az_raw_deg:.3f} x {optics.fov_el_raw_deg:.3f} deg |")
    a(
        f"| Usable FOV after {OPTICS_SPEC.lens_distortion_pct:.2f} % distortion | "
        f"**{optics.fov_az_deg:.3f} x {optics.fov_el_deg:.3f} deg** |"
    )
    a(f"| Half-FOV | +/-{optics.half_az_deg:.3f} deg az, +/-{optics.half_el_deg:.3f} deg el |")
    a(
        f"| 2/3-inch sheet HFOV (8.8 mm, not used) | {optics.datasheet_hfov_deg:.2f} deg "
        f"(computed {optics.computed_2_3_hfov_deg:.3f}) |"
    )
    a(f"| IFOV | {optics.ifov_deg:.5f} deg/px |")
    gsd = h_km * 1000.0 / (OPTICS_SPEC.focal_length_mm / 1000.0) * OPTICS_SPEC.pixel_um * 1e-6
    a(f"| Nadir GSD at design lat (mosaic pixel) | **{gsd:.2f} m** |")
    a(f"| Nadir GSD (2x2 band cell) | {2 * gsd:.2f} m |")
    a(f"| Nadir lateral half-swath | **+/-{r_fit:.2f} km** |")
    a(f"| 2-axis +/-{GIMBAL_BOX.az_box_deg:.0f} deg half-swath | {r_box:.1f} km |")
    a("")
    a("## Along-track time (elevation axis, design pass)")
    a("")
    a(f"Design pass: latitude **{DESIGN_LAT_DEG:.2f} deg**, heading due east,")
    a("Earth rotation almost purely along-track.")
    a("")
    a("| Quantity | Value |")
    a("| --- | --- |")
    a("| Elevation window | 90 -> 30 deg, one-sided, stop at limit |")
    a(f"| Time in elevation window | **{times.along_track_s:.1f} s** |")
    a(f"| Staring at nadir (no gimbal) | {times.stare_s:.2f} s |")
    a(f"| Peak elevation rate | {times.peak_el_rate_deg_s:.3f} deg/s |")
    a(f"| Peak |az| of the origin (Earth rotation) | {times.az_max_deg:.3f} deg |")
    a(f"| Window start / stop from CA | {times.t_start_s:.1f} / {times.t_stop_s:.1f} s |")
    a(
        f"| Slant range at start / stop | "
        f"{times.slant_start_km:.1f} / {times.slant_stop_km:.1f} km |"
    )
    a("")
    a("## Earth rotation vs pass latitude")
    a("")
    a("At low latitude the ISS heading has a large north component, so Earth")
    a("rotation (always east) has a **cross-track** piece. That walks even a")
    a("nadir-centered origin in azimuth, peaking at the 30 deg stop where range")
    a("is long. At max latitude the heading is due east and the walk vanishes.")
    a("That is why a polar-slice one-axis placement is the right one-axis case.")
    a("")
    a(
        "| lat (deg) | h (km) | el window (s) | peak az origin (deg) | "
        "1-axis R=0 (s) | 1-axis R=5 km (s) | 2-axis (s) |"
    )
    a("| --- | --- | --- | --- | --- | --- | --- |")
    for r0, r5 in zip(result.lat_r0, result.lat_r5, strict=True):
        a(
            f"| {r0.lat_deg:.2f} | {r0.alt_km:.1f} | {r0.el_window_s:.1f} | "
            f"{r0.az_max_deg:.3f} | {r0.one_axis_s:.1f} | {r5.one_axis_s:.1f} | "
            f"{r0.two_axis_s:.1f} |"
        )
    a("")
    a("For a point origin, Earth rotation walks it out of the chip below ~40 deg")
    a("latitude. For a 5 km cluster the threshold is ~45 deg. Below that,")
    a("one-axis only keeps the last tens of seconds near nadir. That is a")
    a("2-axis problem, or a choice not to work those passes.")
    a("")
    a("## Plant-cluster covering disk (design pass)")
    a("")
    a("Elevation tracks the cluster CoG. A plume is acquired if it is in the")
    a("frame. The covering radius is `R_cover = D + r` for stack half-span D")
    a("and per-plume CoG radius r. Equal-weight centroid tracking does *not*")
    a("grow with plume count: `R_centroid = r`. The covering disk is the")
    a("stricter (and right) metric if we want every plume in the cluster.")
    a("")
    a("Design R = 5 km: a large integrated complex (~4 km wide, e.g. Baytown")
    a("refinery) plus a few km of plume CoG. Typical small plants are 1-2 km.")
    a("")
    a("| R (km) | peak az (deg) | 1-axis (s) | 2-axis (s) | lost (s) | lost % |")
    a("| --- | --- | --- | --- | --- | --- |")
    for i, radius in enumerate(table.radius_km):
        t1 = float(table.one_axis_s[i])
        t2 = float(table.two_axis_s[i])
        lost = float(table.lost_s[i])
        frac = 0.0 if t2 <= 0 else 100.0 * lost / t2
        a(
            f"| {radius:.1f} | {table.az_peak_deg[i]:.2f} | {t1:.1f} | {t2:.1f} | "
            f"{lost:.1f} | {frac:.1f}% |"
        )
    a("")
    a(f"At the design pass, a disk with **R <= {r_fit:.1f} km** stays in the chip")
    a("for the whole elevation window. Design R = 5 km is **0 s lost**.")
    a("")
    a("Wind during the window:")
    a("")
    a("| wind (m/s) | extra displacement (km) | leftover 1-axis budget (km) |")
    a("| --- | --- | --- |")
    for wind in WIND_MPS:
        extra = (wind / 1000.0) * times.along_track_s
        a(f"| {wind:.0f} | {extra:.2f} | {r_fit - extra:.2f} |")
    a("")
    a("## Off-center cluster (design pass, R = 0)")
    a("")
    a("| origin cross-track (km) | 1-axis (s) | 2-axis (s) | lost (s) |")
    a("| --- | --- | --- | --- |")
    for row in result.offsets:
        a(
            f"| {row.origin_cross_km:.0f} | {row.one_axis_s:.1f} | "
            f"{row.two_axis_s:.1f} | {row.two_axis_s - row.one_axis_s:.1f} |"
        )
    a("")
    a("## Full-frame inference")
    a("")
    a("Optical FOV is the full chip either way. Full-frame inference changes")
    a("compute, not tracking time. The 2x2 band plane is")
    a(f"**{BAND_LATERAL_PX} x {BAND_ALONG_PX}**.")
    a("")
    a("| | 256x256 (today) | full band plane | scale |")
    a("| --- | --- | --- | --- |")
    a(f"| Pixels | {area_256} | {area_ff} | {scale:.1f}x |")
    a(
        f"| DilateNet-w32 FLOPs | {SEG_FLOPS_256_G:.2f} G | "
        f"{SEG_FLOPS_256_G * scale:.2f} G | {scale:.1f}x |"
    )
    a(
        f"| ShuffleNet FLOPs | {CLS_FLOPS_256_G:.3f} G | "
        f"{CLS_FLOPS_256_G * scale:.2f} G | {scale:.1f}x |"
    )
    a(
        f"| CPU accept latency (linear scale from 256) | "
        f"{SEG_LAT_256_MS:.1f} / {CLS_LAT_256_MS:.1f} ms | "
        f"{SEG_LAT_256_MS * scale:.0f} / {CLS_LAT_256_MS * scale:.0f} ms | |"
    )
    a("")
    a("The 500x parameter cut (DilateNet-w32 23.5 k vs U-Net 13.4 M) is what")
    a("makes full-frame plausible. FLOPs still fit the 500 ms budget if latency")
    a("scales with pixels. Jetson Nano (4 GB) is tighter on **activation memory**")
    a("at 1224x1024 than Orin NX; that needs a bench, not a FLOP argument.")
    a("A 256-pixel centre crop on this optic is only ~0.67 deg -- that would")
    a("throw away the 1-axis lateral budget. Full-frame is the right inference")
    a("size for this lens.")
    a("")
    a("## Bottom line")
    a("")
    a(f"1. Along-track, one elevation axis gives **{times.along_track_s:.0f} s**")
    a(f"   at the design (max-lat) pass, vs **{times.stare_s:.1f} s** staring.")
    a("   Stop at 30 deg. Peak rate is under 2 deg/s.")
    a("2. At that pass, Earth-rotation az walk of the origin is")
    a(f"   **{times.az_max_deg:.3f} deg**. A 5 km plant cluster stays in the")
    a(f"   +/-{optics.half_az_deg:.2f} deg chip for the whole window -- **0 s lost**")
    a("   vs two-axis.")
    a("3. At equatorial and mid-latitude passes, Earth rotation walks the")
    a("   origin out at the 30 deg stop. One-axis then keeps only the last")
    a("   ~20-60 s depending on cluster size. Use two-axis for those passes,")
    a("   or do not work them. From ~45 deg up, a 5 km cluster is lossless.")
    a("4. If two plants are farther apart than ~24 km, they are two clusters.")
    a("   Track one.")
    a("5. Worldwide stack inventory (Climate TRACE 2025) is in")
    a("   `INDUSTRIAL.md`. Stack-weighted expected 1-axis loss over the")
    a("   ISS belt is ~59% of the 121 s two-axis window, because ~90% of")
    a("   stacks sit below 45 deg latitude.")
    a("")
    a("## Figures")
    a("")
    a("- `outputs/along_track_timeline.png`")
    a("- `outputs/disk_angular_radius.png`")
    a("- `outputs/tracking_time_vs_radius.png`")
    a("- `outputs/lost_time_vs_radius.png`")
    a("- `outputs/footprint_vs_time.png`")
    a("- `outputs/origin_offset.png`")
    a("- `outputs/required_az_vs_radius.png`")
    a("- `outputs/latitude_earth_rotation.png`")
    a("- `outputs/tracking_time_vs_radius.csv`, `outputs/origin_offset.csv`,")
    a("  `outputs/latitude.csv`")
    a("")
    a("```text")
    a(f"{_RUN_CMD} geometry")
    a("```")
    a("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_industry_report(
    clusters: list[Cluster],
    gem_n: int,
    gppd_n: int,
    ct_n: int,
    fn: TimeLostFn,
    exp: dict[str, dict[str, float]],
    path: Path,
) -> None:
    """Write INDUSTRIAL.md for the worldwide stack inventory.

    Args:
        clusters: World plant clusters.
        gem_n: GEM operating source count (cross-check).
        gppd_n: GPPD thermal plant count (cross-check).
        ct_n: Climate TRACE source count.
        fn: Tracking-time interpolator.
        exp: Expected-time summaries keyed by weight kind.
        path: Output markdown path.

    Returns:
        None.
    """
    iss_i = TLE.inclination_deg
    world = clusters
    iss = [c for c in world if abs(c.lat) <= iss_i]
    lines: list[str] = []
    p = lines.append
    p("# Industrial area vs latitude, and expected tracking time")
    p("")
    p("TEMPORARY ANALYSIS. Generated by the industry command of")
    p(f"`{_RUN_CMD}`.")
    p("")
    p("## Inventory")
    p("")
    p("Primary: Climate TRACE v5.10.0 CO2 **point sources** (2025, monthly summed)")
    p("that actually have smoke stacks:")
    p("")
    p("- combustion electricity generation (coal / gas / oil / biomass / waste)")
    p("- cement, lime, glass")
    p("- iron and steel, aluminum, other metals")
    p("- chemicals, other chemicals, petrochemical steam cracking")
    p("- pulp and paper, other manufacturing")
    p("- oil and gas refining")
    p("")
    p("Oil/gas production, mines, hydro/solar/wind, and food plants are out:")
    p("they are not the industrial-stack plume the payload is built for.")
    p("")
    p("Nearby sources within 8 km are one plant cluster. Clusters wider than")
    p("the chip (~12 km covering radius) are split, matching the earlier rule")
    p("that two plants farther apart than the chip are two tracks. Covering")
    p("radius is `R = D + 2 km` (plant span + plume CoG).")
    p("")
    p("The size assumption is that industrial-area size scales with the")
    p("number of stacks, so the **primary weight is stack count**. Covering-disk")
    p("area over-weights sprawling clusters (pi D^2) and is a sensitivity only.")
    p("Emissions weight how much the plant is actually running.")
    p("")
    p("| Inventory | sources |")
    p("| --- | --- |")
    p(f"| Climate TRACE stack sources | {ct_n} |")
    p(f"| Clusters (after split) | {len(world)} |")
    p(f"| In ISS belt |lat| <= {iss_i:.2f} deg | {len(iss)} |")
    p(f"| GEM operating (cross-check) | {gem_n} |")
    p(f"| GPPD thermal (cross-check) | {gppd_n} |")
    p("")
    p("GEM and GPPD peak in the same 30-40 N band, with ~93% of plants")
    p("inside the ISS belt. The Climate TRACE latitude shape is not an")
    p("OpenStreetMap-Europe artefact.")
    p("")
    p("## World distribution")
    p("")
    p("ISS never nadir-overflies outside +/-51.63 deg. The 2-axis +/-10 deg box adds")
    p("~0.7 deg of latitude at the turning point; ignored here.")
    p("")
    world_area = sum(c.area_km2 for c in world)
    iss_area = sum(c.area_km2 for c in iss)
    world_n = sum(c.n for c in world)
    iss_n = sum(c.n for c in iss)
    world_em = sum(c.emissions_t for c in world)
    iss_em = sum(c.emissions_t for c in iss)
    p("| | world | ISS belt | ISS fraction |")
    p("| --- | --- | --- | --- |")
    p(
        f"| covering area | {world_area:.0f} km2 | {iss_area:.0f} km2 | "
        f"{100.0 * iss_area / max(1, world_area):.1f}% |"
    )
    p(f"| stack sources | {world_n} | {iss_n} | {100.0 * iss_n / max(1, world_n):.1f}% |")
    p(
        f"| 2025 CO2 | {world_em / 1e9:.2f} Gt | {iss_em / 1e9:.2f} Gt | "
        f"{100.0 * iss_em / max(1, world_em):.1f}% |"
    )
    p("")
    p("Stack-weighted mean covering radius in the ISS belt:")
    p(
        f"**{exp['stacks']['mean_r_km']:.2f} km** "
        f"(mean sources/cluster {exp['stacks']['mean_n']:.2f})."
    )
    p("That matches the earlier design R = 5 km.")
    p("Stack fraction at |lat| >= 45 deg (1-axis lossless for a 5 km cluster):")
    p(f"**{100.0 * exp['stacks']['frac_lat_ge_45']:.1f}%**.")
    p("")
    p("### Folded |latitude| (ISS geometry is N/S symmetric)")
    p("")
    p("| |lat| (deg) | stacks | % of ISS-belt | 1-axis R=5 (s) | 2-axis (s) | lost % |")
    p("| --- | --- | --- | --- | --- | --- |")
    bands = ((0.0, 10.0), (10.0, 20.0), (20.0, 30.0), (30.0, 40.0), (40.0, 45.0), (45.0, iss_i))
    iss_n_total = max(1, sum(c.n for c in iss))
    for lo, hi in bands:
        part = [c for c in iss if lo <= abs(c.lat) < hi]
        n_src = sum(c.n for c in part)
        mid = 0.5 * (lo + hi)
        t1, t2, lost = fn.eval(mid, CLUSTER_R_KM)
        frac = 100.0 * n_src / iss_n_total
        lost_pct = 0.0 if t2 <= 0 else 100.0 * lost / t2
        p(f"| {lo:.0f}-{hi:.1f} | {n_src} | {frac:.1f}% | {t1:.1f} | {t2:.1f} | {lost_pct:.0f}% |")
    p("")
    p("## Expected tracking time (ISS-belt clusters, nadir-centered pass)")
    p("")
    p("For each cluster, `time_lost(|lat|, R)` uses the same one-sided 90->30")
    p("deg window, Earth rotation, and hard gimbal stop as the geometry command.")
    p("A pass is assumed over the cluster CoG (best-case origin). Off-track")
    p("origins are a separate loss, captured in the swath column.")
    p("")
    p("| weight | E[T 1-axis] (s) | E[T 2-axis] (s) | E[lost] (s) | lost % | weight at |lat|>=45 |")
    p("| --- | --- | --- | --- | --- | --- |")
    for key, label in (
        ("stacks", "**stack count (primary)**"),
        ("emissions", "2025 CO2"),
        ("area", "covering-disk area (sprawl)"),
    ):
        e = exp[key]
        p(
            f"| {label} | {e['e_t1']:.1f} | {e['e_t2']:.1f} | {e['e_lost']:.1f} | "
            f"{e['e_lost_pct']:.1f}% | {100.0 * e['frac_lat_ge_45']:.1f}% |"
        )
    p("")
    e = exp["stacks"]
    p("ISS dwell (more time near +/-i) does not change the story:")
    p(
        f"stacks + dwell -> E[lost] = **{e['e_lost_dwell']:.1f} s** "
        f"({e['e_t1_dwell']:.1f} vs {e['e_t2_dwell']:.1f})."
    )
    p("")
    p("## Lateral swath (why 2-axis still buys something at 50 deg)")
    p("")
    p("Tracking time is conditional on the cluster being in the frame.")
    p("1-axis only sees +/-1.60 deg (~12 km at nadir). 2-axis sees the +/-10 deg")
    p("box (~76 km). Ground-track spacing is thousands of km, so daily")
    p("longitude coverage is proportional to swath.")
    p("")
    p("| | 1-axis | 2-axis | ratio |")
    p("| --- | --- | --- | --- |")
    p(
        f"| mean daily coverage of a random ISS-belt cluster | "
        f"{100.0 * e['mean_cov1']:.2f}% | {100.0 * e['mean_cov2']:.2f}% | "
        f"{e['mean_cov2'] / max(1e-12, e['mean_cov1']):.2f}x |"
    )
    p(
        f"| yield proxy E[T x coverage] (s x frac) | {e['e_yield1']:.2f} | "
        f"{e['e_yield2']:.2f} | {e['e_yield2'] / max(1e-12, e['e_yield1']):.2f}x |"
    )
    p("")
    p("So even where Earth-rotation azimuth walk is ~0, dropping the azimuth")
    p("axis throws away a factor of ~6 in how much industrial area a given")
    p("day can put in the frame. That is the lateral-motion cost of one axis,")
    p("independent of the along-track 124 s window.")
    p("")
    p("## Decision numbers")
    p("")
    p("1. **Along-track, given a pass over the CoG:** stack-weighted expected")
    p(f"   loss is **{e['e_lost']:.0f} s of {e['e_t2']:.0f} s** ({e['e_lost_pct']:.0f}%).")
    p("   Almost all of that is the 20-40 N band (China, US, Med, India,")
    p("   Japan/Korea), where Earth rotation walks the covering disk out at")
    p("   the 30 deg stop. Only ~10% of stacks sit at |lat| >= 45 deg, where")
    p("   a 5 km cluster is lossless on one axis.")
    p("2. **Lateral, whether we acquire at all:** 2-axis covers ~6x more")
    p("   industrial area per day. One axis only works plants that sit under")
    p("   the 24 km ground-track ribbon. Combined with shorter tracking time,")
    p(
        f"   the yield proxy E[T x coverage] is "
        f"**{e['e_yield2'] / max(1e-12, e['e_yield1']):.1f}x** higher with two axes."
    )
    p("3. A polar-slice one-axis payload that is only tasked at |lat| >= 45 deg")
    p("   keeps the 124 s window, but it is looking at ~10% of the world's")
    p("   stack-bearing industry. If the mission must work the 20-40 N")
    p("   belt, 2-axis is required for the elevation window, not just swath.")
    p("")
    p("## Figures")
    p("")
    p("- `outputs/industrial_lat_hist.png`")
    p("- `outputs/industrial_lat_folded.png`")
    p("- `outputs/industrial_time_vs_lat.png`")
    p("- `outputs/industrial_cluster_radius.png`")
    p("- `outputs/industrial_cluster_map.png`")
    p("- `outputs/industrial_lat_hist.csv`, `outputs/industrial_clusters.csv`")
    p("- `outputs/time_lost_grid.csv` -- the `time_lost(|lat|, R)` table")
    p("")
    p("```text")
    p(f"{_RUN_CMD} industry")
    p("```")
    p("")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
