# ruff: noqa: N802, N803, N999

"""Typed subset of the adjacent, unmodified Xeryon.py implementation."""

from enum import Enum

LIBRARY_VERSION: str

class Units(Enum):
    deg: Units

class Stage(Enum):
    XRTU_40_109: Stage

class Axis:
    def findIndex(self, forceWaiting: bool = ..., direction: int = ...) -> bool: ...
    def setDPOS(
        self,
        value: float,
        differentUnits: object | None = ...,
        outputToConsole: bool = ...,
        forceWaiting: bool = ...,
    ) -> bool: ...
    def getDPOS(self) -> float | None: ...
    def getEPOS(self) -> float | None: ...
    def setUnits(self, units: Units) -> None: ...
    def setSetting(
        self,
        tag: str,
        value: object,
        fromSettingsFile: bool = ...,
        doNotSendThrough: bool = ...,
    ) -> None: ...
    def startScan(
        self, direction: int, execTime: float | None = ..., untilLimit: bool = ...
    ) -> None: ...
    def stopScan(self) -> None: ...
    def setSpeed(self, speed: float) -> None: ...
    def getSetting(self, tag: str) -> object | None: ...
    def getData(self, tag: str) -> object | None: ...
    def isMotorOn(self, external_stat: int | None = ...) -> bool: ...
    def isClosedLoop(self, external_stat: int | None = ...) -> bool: ...
    def isEncoderAtIndex(self, external_stat: int | None = ...) -> bool: ...
    def isEncoderValid(self, external_stat: int | None = ...) -> bool: ...
    def isPositionReached(self, external_stat: int | None = ...) -> bool: ...
    def isScanning(self, external_stat: int | None = ...) -> bool: ...
    def isEncoderError(self, external_stat: int | None = ...) -> bool: ...
    def isAtLeftEnd(self, external_stat: int | None = ...) -> bool: ...
    def isAtRightEnd(self, external_stat: int | None = ...) -> bool: ...
    def isErrorLimit(self, external_stat: int | None = ...) -> bool: ...
    def isThermalProtection1(self, external_stat: int | None = ...) -> bool: ...
    def isThermalProtection2(self, external_stat: int | None = ...) -> bool: ...
    def isSafetyTimeoutTriggered(self, external_stat: int | None = ...) -> bool: ...
    def isPositionFailTriggered(self, external_stat: int | None = ...) -> bool: ...

class Xeryon:
    def __init__(self, COM_port: str | None = ..., baudrate: int = ...) -> None: ...
    def start(
        self,
        external_communication_thread: bool = ...,
        external_settings_default: str | None = ...,
    ) -> None: ...
    def stop(self) -> None: ...
    def stopMovements(self) -> None: ...
    def reset(self) -> None: ...
    def addAxis(self, stage: Stage, axis_letter: str) -> Axis: ...
    def getAxis(self, letter: str) -> Axis: ...
    def readSettings(self, external_settings_default: str | None = ...) -> None: ...
    def setMasterSetting(self, tag: str, value: object, fromSettingsFile: bool = ...) -> None: ...
